# Generated by Django 4.1.4 on 2023-03-12 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autentificacion', '0004_alter_user_address_alter_user_birthdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, default='autentificacion/gato.JPG', null=True, upload_to='autentificacion'),
        ),
    ]
