# Generated by Django 4.1.4 on 2023-02-26 00:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('publicaciones', '0003_remove_solicitudes_valoracion_raking'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Raking',
            new_name='Puntuacion',
        ),
    ]
