# Generated by Django 4.1.4 on 2023-02-26 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0004_rename_raking_puntuacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puntuacion',
            name='valoracion',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
