# Generated by Django 4.1.4 on 2023-02-26 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0005_alter_puntuacion_valoracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicaciones',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
