# Generated by Django 4.1.4 on 2023-05-14 05:24

from django.db import migrations
import publicaciones.models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0007_alter_puntuacion_valoracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicaciones',
            name='precio',
            field=publicaciones.models.PositiveDecimalField(decimal_places=2, max_digits=10),
        ),
    ]
